grunt --build=base --baseFolder=ZEBASE --basePath=nrg
grunt --build=base --baseFolder=ZEBASE_CTRL --basePath=ute/ui
grunt --build=control --controlLibrary=ute.ui.main --controlFolder=ZECTRL_MAIN
grunt --build=control --controlLibrary=ute.ui.commons --controlFolder=ZECTRL_COMMONS
grunt --build=control --controlLibrary=ute.ui.app --controlFolder=ZECTRL_APP
grunt --build=module --moduleName=nrg.module.app --moduleFolder=ZEMOD_APP
grunt --build=module --moduleName=nrg.module.others --moduleFolder=ZEMOD_OTHERS
grunt --build=module --moduleName=nrg.module.dashboard --moduleFolder=ZEMOD_DSHB
grunt --build=module --moduleName=nrg.module.campaign --moduleFolder=ZEMOD_CMPGN
grunt --build=module --moduleName=nrg.module.quickpay --moduleFolder=ZEMOD_QUICKPAY
grunt --build=module --moduleName=nrg.module.billing --moduleFolder=ZEMOD_BILLING
grunt --build=module --moduleName=nrg.module.nnp --moduleFolder=ZEMOD_NNP
grunt --build=module --moduleName=nrg.module.bupa --moduleFolder=ZEMOD_BUPA
grunt --build=module --moduleName=nrg.module.search --moduleFolder=ZEMOD_SEARCH
grunt --build=module --moduleName=nrg.module.usage --moduleFolder=ZEMOD_USAGE
grunt --build=component --componentName=nrg.component.ic --componentFolder=ZECMP_IC
